# Generated by Django 3.0 on 2020-06-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='active',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_status', to='myapi.Emp'),
        ),
        migrations.AlterUniqueTogether(
            name='active',
            unique_together={('emp', 'start_time')},
        ),
    ]
