# Generated by Django 3.0 on 2020-06-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200624_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('ok', models.BooleanField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='emp',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapi.Member'),
        ),
    ]
