# Generated by Django 3.0 on 2020-06-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200624_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapi.Member'),
        ),
    ]
