# Generated by Django 3.0 on 2020-06-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200624_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapi.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='active',
            unique_together=set(),
        ),
    ]
